services:
  web:
    image: liksoft/likos:v16-0-4
    restart: always
    depends_on:
      - db
    ports:
      - "9000:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log
      - odoo-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=liksoft
      - PASSWORD=liksoft
    networks:
      - default
      - karaoking_network
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=liksoft
      - POSTGRES_USER=liksoft
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  odoo-data:

networks:
  default:
    driver: bridge
  karaoking_network:
    external: true
    name: karaoking_default